### ISSUE TITLE
Optinal property 

### ISSUE THREAD

**Issue by Misir8** [dmitriy-nz/nestjs-form-data#12] opened 2021-08-30 04:15 UTC
When updating an entity, I want to make an optional file update. If the user did not add a new file, then leave the old file, and if he added it, then add a new file.

But when I write in the Dto like this:
```
@IsFile()
@IsOptional()
@MaxFileSize(5e6)
@HasMimeType(['image/jpeg', 'image/png', 'image/jpeg'])
@ApiModelPropertyOptional({ type: 'string', format: 'binary' })
readonly image?: Memory Stored File;
```

I get an error:

```
{
  "statusCode": 400,
  "message": [
    "File must be of one of the types image/jpeg, image/png, image/jpeg",
    "Maximum file size is 5000000"
  ],
  "error": "Bad Request"
}
```

**Comment by dmitriy-nz** [comment] 2021-08-30 11:05
I tried to reproduce the problem, everything works as expected, see screenshots.
My DTO class
```
export class AttachmentDto {

  @IsFile()
  @IsOptional()
  @MaxFileSize(5e6)
  @HasMimeType(['image/jpeg', 'image/png', 'image/jpeg'])
  readonly image?: MemoryStoredFile;

}
```
Send request with image field:
Request:
![Выделение_284](https://user-images.githubusercontent.com/51157176/131329620-cdbcaac3-4a76-4e59-a98c-3a24f62a5847.png)
DTO instance in console:
![Выделение_285](https://user-images.githubusercontent.com/51157176/131329684-3935b99b-7e8d-4f99-9c4d-44d57d07504a.png)
Send request without image field:
![Выделение_286](https://user-images.githubusercontent.com/51157176/131329799-1f1a5111-0781-41fc-8841-0af162866e87.png)
DTO instance in console:
![Выделение_287](https://user-images.githubusercontent.com/51157176/131329851-c9bdd92b-2cd2-4615-9922-13daf8ad94e8.png)
it is empty because there are no other fields


Maybe the problem is that you are sending null or any other value in the optional field, then the validator tries to check it. In order for the validator to skip this field, it should not exist in the dto that is sent from the client. Try to check the request through REST Client (postman or insomnia)

**Comment by Misir8** [comment] 2021-08-30 13:08
@dmitriy-nz Thank you very much. I tested only in the swagger ui and always got a validation error there.

**Comment by dmitriy-nz** [comment] 2021-08-30 13:41
You're welcome!
Please check this if all is well close the issue :)

**Closed** 2021-08-30 15:57 UTC
